highlighter: 'pygments'
markdown: kramdown
permalink: none

# Required if you want to move pages into a a separate directory
# not working at the moment for some reason
include: ['_pages']
# relative_permalinks: false


